// Auto generated by Montelo. Do not edit. Run `npx montelo generate` to re-generate.
import getCurrentWeather from "./getCurrentWeather";

export const functions = {
  getCurrentWeather,
};

export const AllFunctions = Object.values(functions).map((func) => func.toJSON());
