// Auto generated by Montelo. Do not edit. Run `npx montelo generate` to re-generate.

import findUser from "./findUser";
import getCurrentWeather from "./getCurrentWeather";
import modifyAppointment from "./modifyAppointment";
import getAppointmentsForUser from "./getAppointmentsForUser";
import createUser from "./user/createUser";

export const functions = {
  findUser,
getCurrentWeather,
modifyAppointment,
getAppointmentsForUser,
createUser
};

export const AllFunctions = Object.values(functions).map((func) => func.toJSON());

