/* tslint:disable */

/* eslint-disable */

/**
 * Montelo
 * Documentation for the Montelo API.
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import type { FullMembershipDto } from "../models/index";
import { FullMembershipDtoFromJSON, FullMembershipDtoToJSON } from "../models/index";
import * as runtime from "../runtime";

/**
 *
 */
export class MembershipApi extends runtime.BaseAPI {
  /**
   */
  async membershipControllerGetAllRaw(
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<runtime.ApiResponse<Array<FullMembershipDto>>> {
    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    if (this.configuration && this.configuration.accessToken) {
      const token = this.configuration.accessToken;
      const tokenString = await token("bearer", []);

      if (tokenString) {
        headerParameters["Authorization"] = `Bearer ${tokenString}`;
      }
    }
    const response = await this.request(
      {
        path: `/membership`,
        method: "GET",
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides,
    );

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      jsonValue.map(FullMembershipDtoFromJSON),
    );
  }

  /**
   */
  async membershipControllerGetAll(
    initOverrides?: RequestInit | runtime.InitOverrideFunction,
  ): Promise<Array<FullMembershipDto>> {
    const response = await this.membershipControllerGetAllRaw(initOverrides);
    return await response.value();
  }
}
