/* tslint:disable */

/* eslint-disable */

/**
 * Montelo
 * Documentation for the Montelo API.
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { exists, mapValues } from "../runtime";

/**
 *
 * @export
 * @interface AuthUserDto
 */
export interface AuthUserDto {
  /**
   *
   * @type {string}
   * @memberof AuthUserDto
   */
  id: string;
  /**
   *
   * @type {string}
   * @memberof AuthUserDto
   */
  firstName: string;
  /**
   *
   * @type {string}
   * @memberof AuthUserDto
   */
  lastName: string;
  /**
   *
   * @type {string}
   * @memberof AuthUserDto
   */
  email: string;
}

/**
 * Check if a given object implements the AuthUserDto interface.
 */
export function instanceOfAuthUserDto(value: object): boolean {
  let isInstance = true;
  isInstance = isInstance && "id" in value;
  isInstance = isInstance && "firstName" in value;
  isInstance = isInstance && "lastName" in value;
  isInstance = isInstance && "email" in value;

  return isInstance;
}

export function AuthUserDtoFromJSON(json: any): AuthUserDto {
  return AuthUserDtoFromJSONTyped(json, false);
}

export function AuthUserDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): AuthUserDto {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    id: json["id"],
    firstName: json["firstName"],
    lastName: json["lastName"],
    email: json["email"],
  };
}

export function AuthUserDtoToJSON(value?: AuthUserDto | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    id: value.id,
    firstName: value.firstName,
    lastName: value.lastName,
    email: value.email,
  };
}
