/* tslint:disable */

/* eslint-disable */

/**
 * Montelo
 * Documentation for the Montelo API.
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { exists, mapValues } from "../runtime";

/**
 *
 * @export
 * @interface CostHistory
 */
export interface CostHistory {
  /**
   *
   * @type {string}
   * @memberof CostHistory
   */
  intervalStart: string;
  /**
   *
   * @type {number}
   * @memberof CostHistory
   */
  totalCost: number;
}

/**
 * Check if a given object implements the CostHistory interface.
 */
export function instanceOfCostHistory(value: object): boolean {
  let isInstance = true;
  isInstance = isInstance && "intervalStart" in value;
  isInstance = isInstance && "totalCost" in value;

  return isInstance;
}

export function CostHistoryFromJSON(json: any): CostHistory {
  return CostHistoryFromJSONTyped(json, false);
}

export function CostHistoryFromJSONTyped(json: any, ignoreDiscriminator: boolean): CostHistory {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    intervalStart: json["intervalStart"],
    totalCost: json["totalCost"],
  };
}

export function CostHistoryToJSON(value?: CostHistory | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    intervalStart: value.intervalStart,
    totalCost: value.totalCost,
  };
}
