/* tslint:disable */

/* eslint-disable */

/**
 * Montelo
 * Documentation for the Montelo API.
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { exists, mapValues } from "../runtime";

/**
 *
 * @export
 * @interface CreateTeamInput
 */
export interface CreateTeamInput {
  /**
   *
   * @type {string}
   * @memberof CreateTeamInput
   */
  name: string;
}

/**
 * Check if a given object implements the CreateTeamInput interface.
 */
export function instanceOfCreateTeamInput(value: object): boolean {
  let isInstance = true;
  isInstance = isInstance && "name" in value;

  return isInstance;
}

export function CreateTeamInputFromJSON(json: any): CreateTeamInput {
  return CreateTeamInputFromJSONTyped(json, false);
}

export function CreateTeamInputFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): CreateTeamInput {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    name: json["name"],
  };
}

export function CreateTeamInputToJSON(value?: CreateTeamInput | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    name: value.name,
  };
}
