/* tslint:disable */
/* eslint-disable */
/**
 * Montelo
 * Documentation for the Montelo API.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DeleteSuccessDto
 */
export interface DeleteSuccessDto {
    /**
     * 
     * @type {boolean}
     * @memberof DeleteSuccessDto
     */
    success: boolean;
}

/**
 * Check if a given object implements the DeleteSuccessDto interface.
 */
export function instanceOfDeleteSuccessDto(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "success" in value;

    return isInstance;
}

export function DeleteSuccessDtoFromJSON(json: any): DeleteSuccessDto {
    return DeleteSuccessDtoFromJSONTyped(json, false);
}

export function DeleteSuccessDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): DeleteSuccessDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'success': json['success'],
    };
}

export function DeleteSuccessDtoToJSON(value?: DeleteSuccessDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'success': value.success,
    };
}

