/* tslint:disable */
/* eslint-disable */
/**
 * Montelo
 * Documentation for the Montelo API.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface EnvironmentDto
 */
export interface EnvironmentDto {
    /**
     * 
     * @type {string}
     * @memberof EnvironmentDto
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof EnvironmentDto
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof EnvironmentDto
     */
    projectId: string;
}

/**
 * Check if a given object implements the EnvironmentDto interface.
 */
export function instanceOfEnvironmentDto(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "id" in value;
    isInstance = isInstance && "name" in value;
    isInstance = isInstance && "projectId" in value;

    return isInstance;
}

export function EnvironmentDtoFromJSON(json: any): EnvironmentDto {
    return EnvironmentDtoFromJSONTyped(json, false);
}

export function EnvironmentDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): EnvironmentDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
        'projectId': json['projectId'],
    };
}

export function EnvironmentDtoToJSON(value?: EnvironmentDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'name': value.name,
        'projectId': value.projectId,
    };
}

