/* tslint:disable */

/* eslint-disable */

/**
 * Montelo
 * Documentation for the Montelo API.
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { exists, mapValues } from "../runtime";

/**
 *
 * @export
 * @interface LoginUserInput
 */
export interface LoginUserInput {
  /**
   * The user's email.
   * @type {string}
   * @memberof LoginUserInput
   */
  email: string;
  /**
   * The user's unencrypted/unhashed password.
   * @type {string}
   * @memberof LoginUserInput
   */
  password: string;
}

/**
 * Check if a given object implements the LoginUserInput interface.
 */
export function instanceOfLoginUserInput(value: object): boolean {
  let isInstance = true;
  isInstance = isInstance && "email" in value;
  isInstance = isInstance && "password" in value;

  return isInstance;
}

export function LoginUserInputFromJSON(json: any): LoginUserInput {
  return LoginUserInputFromJSONTyped(json, false);
}

export function LoginUserInputFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean,
): LoginUserInput {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    email: json["email"],
    password: json["password"],
  };
}

export function LoginUserInputToJSON(value?: LoginUserInput | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    email: value.email,
    password: value.password,
  };
}
