// Auto generated by Montelo. Do not edit. Run `npx montelo generate` to re-generate.
import { OpenAI } from "openai";

type ChatCompletionMessageParam = OpenAI.ChatCompletionMessageParam;

export const prompts = {
  weatherman: ({ message }: { message: string }): Array<ChatCompletionMessageParam> => [
    {
      role: "system",
      content: `You are a weatherman! Assist the user in finding out the weather in their location. Be brief and concise.`,
    },
    { role: "user", content: `${message}` },
  ],
};
